import { defineType, defineField } from 'sanity'

export const decor = defineType({
  name: 'decor',
  title: 'Decor',
  type: 'document',
  description: 'Standalone decor entities with their own content and categorization',
  fields: [
    defineField({
      name: 'code',
      title: 'Decor Code',
      type: 'string',
      validation: (Rule) => Rule.required(),
      description: 'Unique identifier for the decor (e.g., "410", "405")',
    }),
    defineField({
      name: 'name',
      title: 'Decor Name',
      type: 'string',
      validation: (Rule) => Rule.required(),
      description: 'Display name for the decor (e.g., "bianco ghiaccio")',
    }),
    defineField({
      name: 'title',
      title: 'Full Title',
      type: 'string',
      description: 'Full title with code (e.g., "410 - Bianco Ghiaccio")',
    }),
    defineField({
      name: 'image',
      title: 'Decor Image',
      type: 'image',
      options: {
        hotspot: true,
      },
      validation: (Rule) => Rule.required(),
      description: 'Main image showing the decor pattern/texture',
    }),
    defineField({
      name: 'collections',
      title: 'Collections',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Colours', value: 'Colours' },
          { title: 'MEG', value: 'MEG' },
          { title: 'MEG-H', value: 'MEG-H' },
          { title: 'Design Edition', value: 'Design Edition' },
          { title: 'Legni light', value: 'Legni light' },
          { title: 'Legni dark', value: 'Legni dark' },
          { title: 'Hachure', value: 'Hachure' },
          { title: 'HR-LAQ', value: 'HR-LAQ' },
          { title: 'Fabriek', value: 'Fabriek' },
          { title: 'Mare Nostrum', value: 'Mare Nostrum' },
          { title: 'DIGITAL NATURE', value: 'DIGITAL NATURE' },
          { title: 'DIGITAL CIRCUS', value: 'DIGITAL CIRCUS' },
          { title: 'Rocks', value: 'Rocks' },
          { title: 'WHIMSY', value: 'WHIMSY' },
          { title: 'Polaris', value: 'Polaris' },
          { title: 'Polaris Contemporary', value: 'Polaris Contemporary' },
          { title: 'Full colour', value: 'Full colour' },
          { title: 'Metalli', value: 'Metalli' },
          { title: 'PARADE', value: 'PARADE' },
          { title: 'Metal effect', value: 'Metal effect' },
          { title: 'Diafos', value: 'Diafos' },
          { title: 'Labgrade', value: 'Labgrade' },
          { title: 'Labgrade Plus', value: 'Labgrade Plus' },
          { title: 'Magnetico', value: 'Magnetico' },
          { title: 'Interni', value: 'Interni' },
          { title: 'FEBO', value: 'FEBO' },
          { title: 'Naval Deck', value: 'Naval Deck' },
          { title: 'Walkprint', value: 'Walkprint' },
          { title: 'Decori minimi', value: 'Decori minimi' },
          { title: 'Fluo', value: 'Fluo' },
          { title: 'Externa', value: 'Externa' },
          { title: 'Work In Progress', value: 'Work In Progress' },
          { title: 'Polaris Foldline', value: 'Polaris Foldline' },
        ],
      },
      description: 'All collections this decor belongs to (can be multiple)',
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'applicationType',
      title: 'Application Type',
      type: 'array',
      of: [{ type: 'string' }],
      options: {
        list: [
          { title: 'Interior', value: 'interior' },
          { title: 'Exterior', value: 'exterior' },
        ],
        layout: 'grid',
      },
      description: 'Where this decor can be applied (Interior, Exterior, or Both)',
      validation: (Rule) => Rule.required().min(1),
    }),
    defineField({
      name: 'color',
      title: 'Primary Color',
      type: 'string',
      options: {
        list: [
          { title: 'Bianco (White)', value: 'bianco' },
          { title: 'Nero (Black)', value: 'nero' },
          { title: 'Grigio (Grey)', value: 'grigio' },
          { title: 'Beige', value: 'beige' },
          { title: 'Rosa (Pink)', value: 'rosa' },
          { title: 'Rosso (Red)', value: 'rosso' },
          { title: 'Verde (Green)', value: 'verde' },
          { title: 'Giallo (Yellow)', value: 'giallo' },
          { title: 'Arancione (Orange)', value: 'arancione' },
          { title: 'Marrone (Brown)', value: 'marrone' },
          { title: 'Azzurro (Light Blue)', value: 'azzurro' },
          { title: 'Blu (Blue)', value: 'blu' },
          { title: 'Viola (Purple)', value: 'viola' },
          { title: 'Oro (Gold)', value: 'oro' },
        ],
      },
      description: 'Primary color family of the decor',
    }),
    defineField({
      name: 'collectionName',
      title: 'Primary Collection',
      type: 'string',
      description: 'Primary collection name (e.g., "Abet")',
      initialValue: 'Abet',
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 3,
      description: 'Optional description of the decor',
    }),
    defineField({
      name: 'available',
      title: 'Available',
      type: 'boolean',
      description: 'Is this decor currently available?',
      initialValue: true,
    }),
    defineField({
      name: 'featured',
      title: 'Featured Decor',
      type: 'boolean',
      description: 'Display this decor in featured sections',
      initialValue: false,
    }),
    defineField({
      name: 'order',
      title: 'Display Order',
      type: 'number',
      description: 'Order for sorting decors (lower numbers appear first)',
      initialValue: 0,
    }),
  ],
  preview: {
    select: {
      title: 'name',
      code: 'code',
      media: 'image',
      collections: 'collections',
      applicationType: 'applicationType',
      featured: 'featured',
    },
    prepare({ title, code, media, collections, applicationType, featured }) {
      const collectionsText = collections?.slice(0, 2).join(', ') || ''
      const appType = applicationType?.join(' & ') || ''
      
      return {
        title: `${code} - ${title}${featured ? ' ⭐' : ''}`,
        subtitle: `${appType}${collectionsText ? ` • ${collectionsText}` : ''}${collections?.length > 2 ? ` +${collections.length - 2}` : ''}`,
        media,
      }
    },
  },
  orderings: [
    {
      title: 'Featured First',
      name: 'featuredFirst',
      by: [
        { field: 'featured', direction: 'desc' },
        { field: 'order', direction: 'asc' },
        { field: 'name', direction: 'asc' },
      ],
    },
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [
        { field: 'order', direction: 'asc' },
        { field: 'name', direction: 'asc' },
      ],
    },
    {
      title: 'Name A-Z',
      name: 'nameAsc',
      by: [{ field: 'name', direction: 'asc' }],
    },
    {
      title: 'Code A-Z',
      name: 'codeAsc',
      by: [{ field: 'code', direction: 'asc' }],
    },
  ],
})
